### ISSUE TITLE
yaml.parser.ParserError

### ISSUE THREAD

**Issue by ilkkaya** [shaula/rpi-prosody#1]
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 1, column 1
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 1, column 14

**Comment by OsmHydrant** [comment]
Which docker  and docker-compose version do you got?

`docker -v`
`docker-compose -v`

**Comment by shaula** [comment]
Which docker  and docker-compose version do you got?

`docker -v`
`docker-compose -v`

**Comment by shaula** [comment]
Which `docker-compose.yml` file were you using?
