### ISSUE TITLE
Error when running sudo docker run shaula/rpi-prosody

### ISSUE THREAD

**Issue by jbrepogmailcom** [shaula/rpi-prosody#2]
Hello, I understand from docker that image is launched by command **docker run**.

When I use **sudo docker run shaula/rpi-prosody**, I get error 
**************************
A problem occurred while reading the config file /usr/local/etc/prosody/prosody.cfg.lua

Error: /usr/local/etc/prosody/conf.d/04-vhost.cfg.lua:11: attempt to concatenate local 'domain' (a nil value)

More help on configuring Prosody can be found at https://prosody.im/doc/configure
Good luck!
**************************

I run prosody on local network, there is no domain name, only IP address.

**Comment by shaula** [comment]
Using docker run, you should add `-e DOMAIN=your.domain.com`.
See also the docker-compose.yml example within the readme. You could also try to use the local IP address instead.

**Comment by jbrepogmailcom** [comment]
Thank you. I was able to start the image, but I get many errors about certificate because it is incorrectly installed. Do I need access to prosody image filesystem in order to copy certificates to proper directories?

**Comment by shaula** [comment]
No, just map it to the pre-defined location.
