### ISSUE TITLE
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by jbrepogmailcom** [shaula/rpi-prosody#3]
Hello. After I created the docker-compose.yml file and running **docker-compose up -d**, I get error
RROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

Did not use any nonstandard location. Thank you, Jan

**Comment by shaula** [comment]
I guess your docker setup has failed, please check out https://docs.docker.com/toolbox/faqs/troubleshoot/
